# https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/#Using-Docker-Compose

services:
 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    # volumes:
# - pgdata:/var/lib/postgresql/data
#  
# volumes:
#   pgdata:
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

